FROM ghcr.io/fopina/fluent-bit-plugin-dev:v1.9.10 as builder

RUN apt update && apt install -y libc-ares-dev

ADD . /myplugin

RUN cmake -DFLB_SOURCE=/usr/src/fluentbit/fluent-bit-1.9.10/ \
          -DPLUGIN_NAME=in_docker2 ../

RUN make

RUN ls -la

FROM scratch

COPY --from=builder /myplugin/build/flb-in_docker2.so /
