on:
  push:
    branches:
    - 'dev-*'

name: Test build

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          outputs: build
          platforms: linux/amd64,linux/arm64
          file: Dockerfile.build
      - uses: actions/upload-artifact@v3
        with:
          name: test-build
          path: build/
          retention-days: 1
